In [ ]:
## OR1 Lecture 7 Facility Location Problem Example
## Brien Alkire, 20220215
import numpy as np
import cvxpy as cp
m=7 # Num villages
n=3 # Num facility locations
c=np.array([[5,10,7]]) # Facility costs
d=np.array([[4,6,4],   # Aid costs
            [8,12,9],
            [4,3,6],
            [7,4,8],
           [10,2,5],
           [9,4,2],
           [6,7,7]])
# Define the binary (boolean) variables
x=cp.Variable((m,n),boolean=True)
w=cp.Variable((1,n),boolean=True)
# Define the objective and constraints
obj=cp.sum(cp.multiply(x,d))+cp.sum(cp.multiply(w,c)) 
constraints=[cp.sum(x, axis=1)-np.ones((m)) == 0, 
             x-np.ones((m,1))*w <= 0]        
# Formulate and solve
prob=cp.Problem(cp.Minimize(obj),constraints)
prob.solve()
print("The status is",prob.status)
print("Total cost to foundation ($K)",prob.value)
print("The facilities to open are",w.value)
print("The assignment of facilities to villages are \n",x.value)

The status is optimal
Total cost to foundation ($K) 46.0
The facilities to open are [[1. 1. 0.]]
The assignment of facilities to villages are 
 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
print(1/np.exp(1))

0.36787944117144233
