In [ ]:
import numpy as np
A=np.array([[1,2,0],
           [3,-1,-2]])
x=np.array([-1,3,2]).T # Observe we transpose to create a col vector
y=np.array([2,-1]).T
print(A@x) # In Python we use @ for linear algebra multiplication
print(y.T@A)

[  5 -10]
[-1  5  2]


In [ ]:
import numpy as np
M=np.array([[2/3,1/2,1/3], # Markov matrix
            [1/3,0,1/3],
            [0,1/2,1/3]])
x=np.array([1,0,0]).T # Observe we transpose to create a column vector
print(M)
print(x)
print(M@x) # We use the @ symbol for multiplication

[[0.66666667 0.5        0.33333333]
 [0.33333333 0.         0.33333333]
 [0.         0.5        0.33333333]]
[1 0 0]
[0.66666667 0.33333333 0.        ]


In [ ]:
import numpy as np
from numpy import linalg as la
M=np.array([[2/3,1/2,1/3],
            [1/3,0,1/3],
            [0,1/2,1/3]])
d,V=la.eig(M)
print(d)
print(V)
x=V[:,1]/sum(V[:,1]) # We use the second column of V
print(x)

[-0.33333333  1.          0.33333333]
[[ 1.96116135e-01  8.74157276e-01 -7.07106781e-01]
 [-7.84464541e-01  3.88514345e-01 -9.57747421e-17]
 [ 5.88348405e-01  2.91385759e-01  7.07106781e-01]]
[0.5625 0.25   0.1875]


In [10]:
import time
import numpy as np
from numpy import linalg as la
n=1000
m=30
np.random.seed(0)
elapsed=np.zeros(m)
for j in range(0,m):
  A=np.random.rand(n,n)
  tic=time.perf_counter()
  d,V=la.eig(A)
  toc=time.perf_counter()
  elapsed[j]=toc-tic
print(f"Average time {np.mean(elapsed):0.4f} seconds, standard deviation {np.std(elapsed):0.4f} seconds")


Average time 1.9731 seconds, standard deviation 0.0447
